### PR TITLE
closes #72

### LINKED ISSUE #72: View conf.js rework
The current conf.js assumes a simple list and details view for each class. A more flexible approach allows displays to be defined with more flexibility and with transitions between displays. This covers only the API description of the file for the basic, first step of building a view.

### PR DESCRIPTION
**Pull request by ohler55**
Initial cut at describing a flow configuration file.

The additions were made as if part of the tutorial. I think that is were it makes the most sense for now. It can be changed later if needed.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Is the tutorial going to be hosted on GitHub Pages
If yes, its best transformed into a jekyll site to avoid typing out the complete HTML for every new `index.html`

**Comment by ohler55** [comment]
I don't expect the html is going to change so that is not really an issue. There will be multiple versions of the config.js file and the controller.rb file. Its not really part of this PR but let me describe what I think we want for the tutorial.

1) Markdown files that are the tutorial guide and descriptions. This could be HTML I suppose but markdown seemed simpler.
2) Images and diagrams. They need to be served from somewhere.Maybe wab.systems or Jekyll.
3) File expected to be created for that lesson. They should be able to be downloaded or checked out.

I think that is it.

**Comment by ashmaroli** [comment]
> multiple versions of the config.js file and the controller.rb file

that's the scary bit (at least for the uninitiated..)

**Comment by ohler55** [comment]
Multiple versions only because they get more detailed from lesson to lesson. New features have to be added somewhere.

**Pull request merged**
