### PR TITLE
Update CI configs

### PR DESCRIPTION
**Pull request by ashmaroli**
Travis does all these steps by default

### CODE REVIEW

**Comment by ohler55** [comment]
It doesn't look like the ioshell_test.rb file was run. If we are going to rely only on the rake file then it should execute tests.rb instead of impl_test.rb.

**Comment by ashmaroli** [comment]
> It doesn't look like the ioshell_test.rb file was run.

What makes you say that?

**Comment by ashmaroli** [comment]
Nevermind..

**Comment by ohler55** [comment]
Counted the dots and the Rakefile. Looks like you noticed too. :-)

**Comment by ashmaroli** [comment]
I was under the impression that `impl_test.rb` was all that was needed to be run.. `ioshell_test` seemed like a sanity-check..

**Comment by ashmaroli** [comment]
The Travis failures are inconsistent across multiple Travis builds. I suspect a Race Condition at play here..

**Comment by ohler55** [comment]
Odd, I thought I replaced the match? already. LGTM

**Comment by ashmaroli** [comment]
You did replace some of them.. :wink:
Any idea regarding the random Travis failures?

**Comment by ohler55** [comment]
Will look at that later today. They are tough to debug but it could explain the benchmark inconsistencies as well.

**Pull request merged**
