### PR TITLE
Use `attr_reader` method for getter methods

### PR DESCRIPTION
**Pull request by ashmaroli**
Adopting the use of `attr_reader`, `attr_writer` and `attr_accessor` methods will allow you do less typing later

### CODE REVIEW

**Comment by ashmaroli** [comment]
If you're cool with this, then we can set `attr_writer` or `attr_accessor` method for `controllers` in `WAB::Shell` as well..

**Comment by ohler55** [comment]
I am currently working on a stdio branch and have made changes to shell. Merged shell, view, and model. Fewer parts. Should have something that kind of works in a week or so.

**Comment by ohler55** [comment]
As we discussed the shell is a duck type template for implementations. As such it should not have any auto-generated methods.

**Comment by ashmaroli** [comment]
In my defense, overlooking the scope of a class designated as "duck type template", methods obtained with `attr_reader` are not auto-generated. They're identical to those obtained by `def..end` blocks with just an `instance_variable`, the advantage being, the former is more concise.

**Comment by ohler55** [comment]
I know there is no way to read my mind and I agree the end result is the same. I think the documentation is more straight forward for someone wanting to implement later. Just my opinion though.

**Pull request closed without merging**
