### PR TITLE
Placeholder markup and styles

### PR DESCRIPTION
**Pull request by ashmaroli**
wabr

(remove the ``id="view"` and uncomment markup to preview above locally..)

### CODE REVIEW

**Comment by ohler55** [comment]
So use ul and li for the items it typical. How about for a list, ul and li again?

**Comment by ashmaroli** [comment]
Currently the markup is for objects and nested objects.. if value is an array or string, additional styling will be required..

**Comment by ohler55** [comment]
I was thinking about the list of objects.

**Comment by ashmaroli** [comment]
hmm.. it'd be like `<ul><li></li></ul>` for each list item..

**Comment by ohler55** [comment]
Fair enough, wasn't sure if that made the most sense or if div was better.

**Comment by ashmaroli** [comment]
can change based on what is to be rendered..

**Comment by ohler55** [comment]
No worries for now. This is the first cut. In a couple of days we should have it all working end to end. Basic but working.

**Comment by ohler55** [comment]
Travis and rake are still not playing together nicely.

**Pull request merged**
