### PR TITLE
Run Travis with a shell script

### PR DESCRIPTION
**Pull request by ashmaroli**
ditching Rake test task for a simple shell script

### CODE REVIEW

**Comment by ohler55** [comment]
Let's see if this does better on Travis. Thanks.

**Comment by ohler55** [comment]
Odd, one appveyor test has not finished for status. I'll check when I get home. Can't merge from the phone without it passing.

**Comment by ohler55** [comment]
Looks like appveyor/branch should not be part of status.

**Comment by ashmaroli** [comment]
yeah.. even I was wondering why the status is looking towards a non-existing branch..

**Pull request merged**
