### PR TITLE
Add markup and style blueprints for list-table

### PR DESCRIPTION
**Pull request by ashmaroli**
Highlights:
  - created an icon-font using IcoMoon App. This will us to easily use only those icons we're actually using and future icons can be easily added using the `selection.json` also checked into the assets directory. Details in `assets/wabfont/README` 

wab-view-table

### CODE REVIEW

**Comment by ohler55** [comment]
Looks good. I'll get it hooked up today. Not sure how much will be templated though. Buttons probably. A single td might be more trouble that its worth.

**Comment by ashmaroli** [comment]
it's not a single `<td>`.. rather 3 `<td>` capped with a single `<th>`

**Comment by ohler55** [comment]
I was looking at the individual rows. 5 ```<td>```. The buttons should be fine as templates but the attributes only have text in the ```<td>``` so creating the element and then adding a string as innerHTML is the same as just adding the string as a child.

**Comment by ashmaroli** [comment]
that should do fine for a simple render now

**Pull request merged**
