### PR TITLE
Abstract shell-logger methods to a module

### PR DESCRIPTION
**Pull request by ashmaroli**
Move shell-logger methods to a module instead of defining them multiple times

### CODE REVIEW

**Comment by ohler55** [comment]
I like all the changes except the WAB::Shell. Since it is intended as a duck-type it should not implement any real behavior. Pulling in the ShellLogger forces an implementation on anyone that tries to write a different shell. Particularly an C extension shell.

I like the forward trick although, with that is it even necessary to make the ShellLogger module? Either way is fine though. Nice cleanup.

**Comment by ashmaroli** [comment]
> all the changes except the WAB::Shell. Since it is intended as a duck-type it should not implement any real behavior

:smiley: I keep forgetting that `WAB::Shell` is duck-typed.. I revert the patch for `WAB::Shell`


> is it even necessary to make the ShellLogger module

I don't think a Class can be `included`/`extended` into another Class

**Comment by ohler55** [comment]
The question was not class vs module. It was since the meat of the module is only two lines, the attributes_accessor and the forward, maybe just that in the IO::Shell and Impl::Shell.

**Comment by ashmaroli** [comment]
> maybe just that in the IO::Shell and Impl::Shell

I prefer to use `include` since its DRY and we have a single point of definition. Any future changes need be done only in the module.. We can split it in future if the two Shells require differing logger methods

**Pull request merged**
