### PR TITLE
OptionParser handles lack of short opt gracefully

### PR DESCRIPTION
**Pull request by ashmaroli**
I recommend that you try this patch locally.. there's no difference in generated Help menu with this and with `develop`

### CODE REVIEW

**Comment by ohler55** [comment]
If you go back to the original that is the way I had it. It did not work correctly. You could not pick that option.

**Comment by ashmaroli** [comment]
I stand corrected.. :grimacing:

**Comment by ohler55** [comment]
Never hurts to check.

**Comment by ashmaroli** [comment]
I *assumed* all is well because the help menu looked identical.. :trollface:

**Pull request closed without merging**
