### PR TITLE
Sketch out possible directory layout for a WAB App

### PR DESCRIPTION
**Pull request by ashmaroli**
Outlining a possible layout for a WAB app..
This PR will serve as documentation for the genesis of the future App structure.

### Back-end

Of the directories listed, two directories `controllers` and `configs` are of vital importance to WAB. Their contents form the "heart" of the App.
If `controllers` is empty, WAB falls back to `OpenController` **unless** a controller key is defined in the config file.
The `configs` directory can contain either a `*.conf` file, or a JSON file or a YAML file. If no config file is passed via the terminal, then WAB looks for a `./configs/wab.conf` >`./configs/wab.json` > `configs/wab.yml` in that order.

### Front-end

The `assets` dir is where the "front-end" of the App is located. It can be named anything, its sub-directories can be named anything. Just that the contents should be linked to the `./index.html` as appropriate.

WAB doesn't compile Sass out-of-the-box (yet). `css` houses the stylesheet(s).
WAB doesn't compile CoffeeScript or other JS preprocessors. `js` houses the vanilla JS. In the sample-app, ES2015 (or ES6) JS code is housed in subdirectory `js-next` with corresponding ES5 or current-widespread flavor at the root of `js` as a fallback for older browsers.

### CODE REVIEW

**Comment by ohler55** [comment]
There are really several sets of files that need to be covered.

1) wabur source for view which is now in the view directory.
2) built and deployed code (es6, js, css, wabfonts)
3) app files. A wabur-init script should set that up at some point.

Now some comments.

1) Why `configs` instead of `config` that we have been using?
2) What is js-next or maybe why is the better question?
3) Traditionally Ruby code goes in a `lib` directory. Is there a reason to change that to `controllers`? I say that because as project grow I would expect other support code will be written by the users other than just the controllers themselves.
4) Automagically setting up controllers will be a problem unless some naming convention is used as controllers need to be associated with a URL path or paths. That is not something that can be figured out without some hints somewhere such as in the configuration files. As pointed out in item 3 above I expect there will be more Ruby files than just the controllers in the directory.

**Comment by ohler55** [comment]
I noticed something else, the Ruby code and configuration files are part of the served content. They should be separate. That the reason the `pages` directory was used in the sample or view directory.

**Comment by ashmaroli** [comment]
Thanks for the feedback. Regarding the comments:

  1. `config` will do fine as well. Used the plural because it could contain multiple config files.
  2. `js-next` because `es6` is not future-proof.. In future, it will be `ES2016`, or `ES2017`, etc.. but `js-next` always denotes the bleeding-edge JS.
  3. Agree with the `lib` dirname for Ruby files as well. But I hoped to keep the `config` directory and `controllers` directory close to each other as a group.
  4. Naming convention is a good thing. That promotes a pattern and will make things easier while developing and debugging. If `lib/controllers/` is a better fit for the convention, that's fine too.

**Comment by ohler55** [comment]
:-) just noticed the auto-correct. I meant `conf` non `config`.

**Comment by ashmaroli** [comment]
isn't `config` better since it can house either or all of the three formats..?

**Comment by ohler55** [comment]
2) Code that is es6 now will be es6 in the future. js-next does not make clear what version of code is in there. Who know maybe some day there will be both es6 and ES2017. I think a clear version in the name or suffix is better.
3+4) maybe `lib/controllers` would be better. That does force a module name on the user though. Maybe thats okay since it is only a convention.

**Comment by ohler55** [comment]
config vs conf) you might be right. Certainly spell-correct thinks you are.

**Comment by ashmaroli** [comment]
> does not make clear what version of code is in there

that was not the primary intention. The primary intention was to segregate future-JS and current-JS, the latter of which will be served to browsers that do not support future JS..

**Comment by ashmaroli** [comment]
> That does force a module name on the user though

How so..?

**Comment by ohler55** [comment]
Ruby convention is module names follow directory structure.

**Comment by ohler55** [comment]
Some good news that might help deciding on a layout. Browsers are glad to load wab.es6 as long as the mime type is `application/javascript`. OpO handles it and WEBrick should if a servlet is written. Looks like a servlet is needed for cross site anyway.

**Comment by ashmaroli** [comment]
...and Chrome 61 now comes with native support for ES6 Modules :tada:

**Comment by ohler55** [comment]
Lets assume we can keep a wab.es6 and wab.js in the same directory. The paths look cleaner that way. Less confusion about which is es6 and which is es5.

**Comment by ashmaroli** [comment]
since the extensions are different, the OS filesystem is not going to have a problem with them in the same directory..

 - [x] `configs => config`
 - [x] Merge the two js subfolders

**Comment by ohler55** [comment]
Of course our intent is to have the css, font, and wab related assets served remotely.

**Comment by ashmaroli** [comment]
That shouldn't affect the directory layout.. as long as the assets are properly referenced in the `index.html`

**Comment by ashmaroli** [comment]
is the following possible?
```javascript
import foo from './foo.es6'

console.log(foo('bar'));
```

**Comment by ohler55** [comment]
yes, as long as the server says the `content-type` is `application/javascript`. Worked with wab and ui.

**Comment by ohler55** [comment]
I think this PR served it's purpose and can be closed without merging at this point.

**Pull request closed without merging**
