### PR TITLE
Shell Logging

### PR DESCRIPTION
**Pull request by ohler55**
Method for logging through the shell were added to the WAB::Shell duck-type.
This allows more consistent logging with the IO, Impl, and C shells.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Instead of defining two new instances of `Logger` and then repeat the method definitions, why not define a base class and then initialize two logger sub classes of that base class?

**Comment by ohler55** [comment]
I debated about that. I wasn't sure where the base/common class would go. I don't want it in the WAB directory. Maybe IO could depend on Impl. What do you think?

**Comment by ashmaroli** [comment]
> I don't want it in the WAB directory

ideally classes under the `WAB` namespace would be placed in the WAB directory.. but since you do not want to place it there, I do not see a better alternative.

Also, I think the two modules `IO` and `Impl` best remain exclusive..

**Comment by ohler55** [comment]
I would prefer to have a base but am not sure where to put it. I'm with you on it not being what we want though.

**Comment by ashmaroli** [comment]
its a `WAB` specific logger that can be used throughout the library.
`WAB::Logger` like how we have `WAB::Error`..

**Comment by ohler55** [comment]
Maybe. At least for the ruby shells. Would be a module I suppose. Want to take a shot at it?

**Comment by ashmaroli** [comment]
sure.. Fine with a `WAB;;Logger` class at `./lib/wab/logger.rb`?

**Comment by ohler55** [comment]
The idea was to have methods on the shell. I suppose it could be a separate logger but then just the ruby logger would be enough. Thinking ou loud... So looking at the use cases it is either `shell.warn ('hello')` or `shell.logger.warn ('hello')`. The separate logger makes the C shell/runner more complex but ruby simpler. It also forces the ruby logger ATI onto the C runner. More musing... although a Wab logger could limit the calls to a subset of the ruby logger.

What are your thoughts?

**Comment by ashmaroli** [comment]
One other way is to create a module for these logger shell-methods and then mixin the module into the required classes..
```ruby
module WAB
  module ShellLogger
    # ...
  end
end
```
```ruby
class WAB::IO::Shell
  include WAB::ShellLogger
  # existing regular shell methods
end
```
repeat into `Impl::Shell`

**Comment by ohler55** [comment]
I think that is a good approach.

**Pull request merged**
