### PR TITLE
IO Engine cleanup

### PR DESCRIPTION
**Pull request by ashmaroli**
- remove unnecessary parantheses after method calls
- move repeating steps to private methods

### CODE REVIEW

**Comment by ashmaroli** [comment]
IMO, the `:process_msg` method here is too long.. and also on the fence about `rescu`ing from `Exception`

**Comment by ohler55** [comment]
The process_msg method fits on a page easily. That seems small enough. As for rescue of Exception, the controller can raise anything and it should not kill the loop. If the loop quits the shell is as good as done.

**Comment by ohler55** [comment]
Want me to merge this now before calling it a day?

**Comment by ashmaroli** [comment]
k.. you may merge..

**Pull request merged**
