### PR TITLE
Support different input types

### PR DESCRIPTION
**Pull request by ohler55**
Single value input types are supported and are converted to the correct
type in the create and update action. Some renaming was done on the Javascript
functions.

### CODE REVIEW

**Comment by ashmaroli** [comment]
`httpGet` and `httpDelete` are similar functions with a few minor changes.. guess they can be merged into a single function.. but that's for another PR..

**Comment by ohler55** [comment]
Could merge httpGet and httpDelete and take another arg. Maybe another PR.

**Comment by ashmaroli** [comment]
yes.. will send the PR shortly..

**Comment by ohler55** [comment]
:-)

**Pull request merged**
